import { money, monthLabel } from "./logic";

export function Dashboard({ state, rows, revenue, costs, ending, high, setScenario, setDelay, onExport }) {
  return <>
    <header className="top"><div><p>Finance operations workspace</p><h1>Revenue Forecast & Cashflow Control</h1></div><button onClick={onExport}>Export TXT report</button></header>
    <section className="hero"><div><p>Forecast scenario</p><h2>{state.scenario} outlook</h2><span>Models project delivery, receivable confidence, renewal probability, scope-change pipeline, and operating costs.</span><div className="scenario">{["conservative","expected","aggressive"].map(name=><button key={name} className={state.scenario===name?"selected":""} onClick={()=>setScenario(name)}>{name}</button>)}</div></div><div className="orbit"><b>{money(ending)}</b><small>Dec closing cash</small></div></section>
    <section className="metrics"><article><small>Forecast revenue</small><b>{money(revenue)}</b><span>Jul–Dec scenario forecast</span></article><article><small>Forecast costs</small><b>{money(costs)}</b><span>Operating cost plan</span></article><article className={high.length?"risk":""}><small>Collection alerts</small><b>{high.length}</b><span>High-risk invoices</span></article><article><small>Closing cash</small><b>{money(ending)}</b><span>End of forecast</span></article></section>
    <section className="cash card"><div className="heading"><p>Monthly cash forecast</p><h2>Revenue and cash position</h2></div><div className="table"><div className="thead"><span>Month</span><span>Projects</span><span>Invoices</span><span>Renewals</span><span>Changes</span><span>Costs</span><span>Closing cash</span></div>{rows.map(r=><div className="tr" key={r.month}><b>{monthLabel(r.month)}</b><span>{money(r.project)}</span><span>{money(r.invoice)}</span><span>{money(r.renewal)}</span><span>{money(r.change)}</span><span>{money(r.costs)}</span><strong className={r.closingCash<state.openingCash*.6?"negative":""}>{money(r.closingCash)}</strong></div>)}</div></section>
    <section className="sim card"><p>Late payment simulator</p><h2>What if an invoice is late?</h2><label>Invoice<select value={state.delayedInvoiceId} onChange={e=>setDelay(e.target.value,state.delayedDays)}><option value="">No simulated delay</option>{state.invoices.map(i=><option key={i.id} value={i.id}>{i.client} · {money(i.amount)}</option>)}</select></label><label>Delay days<input type="number" min="0" value={state.delayedDays} onChange={e=>setDelay(state.delayedInvoiceId,Number(e.target.value)||0)}/></label><span>Scenario changes only the forecast; it does not alter the original invoice record.</span></section>
  </>;
}
